### ISSUE TITLE
Small glitch in file path calculation

### ISSUE THREAD

**Issue by hendrikstier** [rubyworks/rspec-ontap#2]
Line 88 in ontap.rb:

> file = self.class.relative_path(file)

This statement fails (NoMethodError). Commenting it out has the lib running (ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14] / rspec-ontap (0.3.0) ).

**Comment by trans** [comment]
Hmm... I wonder how that happened. Not sure, but I think I fixed it by getting rid of `self.class.` part.
